<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ0ZQZHP\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ0ZQZHP/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerZ0ZQZHP.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerZ0ZQZHP\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerZ0ZQZHP\appAppKernelProdContainer([
    'container.build_hash' => 'Z0ZQZHP',
    'container.build_id' => '011ac546',
    'container.build_time' => 1721349111,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ0ZQZHP');
