<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtwVwhLC5zunh03zh8Ea0'."\n".'9OdEhFnG5aMc/6yE/FKIvvY/Fwhdgm/LvOFl9301hbfTL+n6BvVbuSPMWAW0s7UW'."\n".'yQCPH0kazwHmQBGPfffs0fWnqAIlN9Jgs+1eFYFGeKEgTjUINOc7APcR4zjWLsIg'."\n".'KgqJCn24DwQHlN48utSB/LxShdONiLMK9J40JQApiYnqyTjI0FdI8N3NeRTrYw0u'."\n".'8X1HjcOalTwEkoW9DwhnM2VX78Kg7A+oazTkqNd7j+g4p14GHsfVYpMkJzc9I5l1'."\n".'ntbuXmSaWD+hf5JWLACqv8a18vb8y2wTAK3OA6QJBLOnb+dgWxdyKwYXtbaDGK+k'."\n".'aQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
